version: '3.8'
services:
  web:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=myapp
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
